/**
 * Isomorphic markdown → HTML pipeline for study notes.
 *
 * Order matters:
 *   1. fenced code blocks  → figure placeholders (rendered as SVG images)
 *   2. display math $$..$$ → katex
 *   3. inline math $..$    → katex
 *   4. <br> passthrough (only allowed raw HTML)
 *   5. cross-ref markers `[[KUHS-QUESTION:CODE:Qnn]]` + bare [CODE:Qnn] → link chips
 *   6. escape remaining `<` (no other raw HTML passes through)
 *   7. marked (GFM)
 *   8. placeholder → generated HTML substitution
 *
 * Everything that reaches the final HTML is either produced by marked from
 * escaped text or generated by this module from the bank's own data, so the
 * output is safe to inject without a DOM-based sanitizer (works on the
 * server, where window is unavailable).
 */
import { marked } from "marked";
import katex from "katex";
import type { NoteRef } from "./bank";

marked.setOptions({ gfm: true, breaks: false });

export type RenderedNote = {
  html: string;
  codeBoxes: string[];
  unresolvedRefs: { code: string; qnum: number }[];
};

const REF_MARKER = /\[\[KUHS-QUESTION:(\d{6}):Q(\d{1,2})\]\]/g;
const BARE_CITATION_LIST = /(?<!\[)\[(\d{6}:Q\d{1,2}(?:\s*,\s*\d{6}:Q\d{1,2})*)\](?!\])/g;

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function token(kind: string, i: number): string {
  return `@@${kind}${i}@@`;
}
const TOKEN_RE = /@@(CB|MATH|REF|BR)(\d+)@@/g;

/** Build an SVG image (data URI) that faithfully draws an ASCII diagram. */
export function codeBoxToSvgDataUri(code: string): string {
  const lines = code.replace(/\n+$/, "").split("\n");
  const fs = 13;
  const lh = Math.round(fs * 1.38);
  const chW = fs * 0.6;
  const pad = 14;
  const maxLen = Math.max(1, ...lines.map((l) => l.length));
  const w = Math.ceil(maxLen * chW + pad * 2);
  const h = Math.ceil(lines.length * lh + pad * 2 - (lh - fs));
  const text = lines
    .map(
      (l, i) =>
        `<text x="${pad}" y="${Math.round(pad + fs * 0.85 + i * lh)}" font-family="Menlo,Consolas,'DejaVu Sans Mono','Courier New',monospace" font-size="${fs}" fill="#e8e3d8" xml:space="preserve">${esc(l)}</text>`,
    )
    .join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="#141a17" rx="6"/>${text}</svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

function refHtml(code: string, qnum: number, refs: NoteRef[] | undefined, unresolved: RenderedNote["unresolvedRefs"]): string {
  const nn = String(qnum).padStart(2, "0");
  const hit = refs?.find((r) => r.code === code && r.qnum === qnum);
  if (hit && hit.id) {
    const paperId = hit.id.split("__")[0];
    const shortLabel = hit.label.split("—")[0].trim();
    const title = hit.label.split("—").slice(1).join("—").trim();
    return `<a class="xref" href="/paper/${paperId}?q=${encodeURIComponent(hit.id)}" data-target="${hit.id}" title="${esc(title)}">${esc(shortLabel)}<span class="xref-title">${esc(title)}</span></a>`;
  }
  unresolved.push({ code, qnum });
  return `<span class="xref xref-plain">${code} Q${nn}</span>`;
}

export function renderNote(content: string, refs?: NoteRef[]): RenderedNote {
  const codeBoxes: string[] = [];
  const math: string[] = [];
  const unresolved: RenderedNote["unresolvedRefs"] = [];
  const refPayloads: { code: string; qnum: number }[] = [];
  const brs: true[] = [];

  // structured-format metadata tags (stripped at build; kept as a safety net)
  let text = content.replace(/^%%(PAPER:|END(\s|%%|$)).*$/gim, "");

  // 1. fenced code blocks (before math: diagrams can contain $ or backslashes)
  text = text.replace(/```[a-zA-Z]*\r?\n([\s\S]*?)```/g, (_m, code: string) => {
    codeBoxes.push(code.replace(/\s+$/, ""));
    return `\n\n${token("CB", codeBoxes.length - 1)}\n\n`;
  });

  // 2. display math $$...$$ (may span lines)
  text = text.replace(/\$\$([\s\S]+?)\$\$/g, (_m, tex: string) => {
    math.push(tex);
    return `\n\n${token("MATH", math.length - 1)}\n\n`;
  });

  // 3. inline math $...$ (single line, non-empty)
  text = text.replace(/\$([^$\n]+?)\$/g, (_m, tex: string) => {
    math.push(tex);
    return token("MATH", math.length - 1);
  });

  // 4. allow-listed <br>
  text = text.replace(/<br\s*\/?>/gi, () => {
    brs.push(true);
    return token("BR", brs.length - 1);
  });

  // 5a. strip backticks the source wraps around ref markers
  text = text.replace(/`(\[\[KUHS-QUESTION:\d{6}:Q\d{1,2}\]\])`/g, "$1");
  text = text.replace(REF_MARKER, (_m, code: string, qn: string) => {
    refPayloads.push({ code, qnum: Number(qn) });
    return token("REF", refPayloads.length - 1);
  });
  // 5b. bare citations like [101001:Q02] and lists like [101001:Q02, 111001:Q05]
  text = text.replace(BARE_CITATION_LIST, (_m, inner: string) =>
    inner
      .split(/\s*,\s*/)
      .map((el) => {
        refPayloads.push({ code: el.slice(0, 6), qnum: Number(el.split(":Q")[1]) });
        return token("REF", refPayloads.length - 1);
      })
      .join(", "),
  );

  // 6. escape remaining raw HTML (placeholders are plain-text safe)
  text = text.replace(/</g, "&lt;");

  // 7. markdown
  let html = marked.parse(text) as string;

  // 8. substitute placeholders
  html = html
    .replace(new RegExp(`<p>\\s*(${TOKEN_RE.source})\\s*</p>`, "g"), "$1")
    .replace(new RegExp(TOKEN_RE.source, "g"), (full, kind: string, numStr: string) => {
      const i = Number(numStr);
      if (kind === "CB") {
        const uri = codeBoxToSvgDataUri(codeBoxes[i]);
        return `<figure class="code-diagram"><img src="${uri}" alt="Hand-drawn study diagram (ASCII source preserved in PDF export)" loading="lazy" draggable="false"/></figure>`;
      }
      if (kind === "MATH") {
        try {
          return katex.renderToString(math[i], { throwOnError: false, output: "html", strict: "ignore" });
        } catch {
          return `<code>${esc(math[i])}</code>`;
        }
      }
      if (kind === "REF") {
        const p = refPayloads[i];
        return refHtml(p.code, p.qnum, refs, unresolved);
      }
      if (kind === "BR") return "<br/>";
      return full;
    });

  return { html, codeBoxes, unresolvedRefs: unresolved };
}
