/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesSubjectRouteImport } from './routes/notes.$subject'
import { Route as PaperIdRouteImport } from './routes/paper.$id'
import { Route as SubjectSubjectRouteImport } from './routes/subject.$subject'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsKeyRouteImport } from './routes/topics.$key'
import { Route as YearYearRouteImport } from './routes/year.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSubjectRoute = NotesSubjectRouteImport.update({
  id: '/notes/$subject',
  path: '/notes/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperIdRoute = PaperIdRouteImport.update({
  id: '/paper/$id',
  path: '/paper/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectRoute = SubjectSubjectRouteImport.update({
  id: '/subject/$subject',
  path: '/subject/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsKeyRoute = TopicsKeyRouteImport.update({
  id: '/topics/$key',
  path: '/topics/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const YearYearRoute = YearYearRouteImport.update({
  id: '/year/$year',
  path: '/year/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/pdf': typeof ApiPdfRoute
  '/notes/$subject': typeof NotesSubjectRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/topics/$key': typeof TopicsKeyRoute
  '/year/$year': typeof YearYearRoute
  '/notes/': typeof NotesIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/pdf': typeof ApiPdfRoute
  '/notes/$subject': typeof NotesSubjectRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/topics/$key': typeof TopicsKeyRoute
  '/year/$year': typeof YearYearRoute
  '/notes': typeof NotesIndexRoute
  '/topics': typeof TopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/pdf': typeof ApiPdfRoute
  '/notes/$subject': typeof NotesSubjectRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/topics/$key': typeof TopicsKeyRoute
  '/year/$year': typeof YearYearRoute
  '/notes/': typeof NotesIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/pdf'
    | '/notes/$subject'
    | '/paper/$id'
    | '/subject/$subject'
    | '/topics/$key'
    | '/year/$year'
    | '/notes/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/pdf'
    | '/notes/$subject'
    | '/paper/$id'
    | '/subject/$subject'
    | '/topics/$key'
    | '/year/$year'
    | '/notes'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/api/pdf'
    | '/notes/$subject'
    | '/paper/$id'
    | '/subject/$subject'
    | '/topics/$key'
    | '/year/$year'
    | '/notes/'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPdfRoute: typeof ApiPdfRoute
  NotesSubjectRoute: typeof NotesSubjectRoute
  PaperIdRoute: typeof PaperIdRoute
  SubjectSubjectRoute: typeof SubjectSubjectRoute
  TopicsKeyRoute: typeof TopicsKeyRoute
  YearYearRoute: typeof YearYearRoute
  NotesIndexRoute: typeof NotesIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$subject': {
      id: '/notes/$subject'
      path: '/notes/$subject'
      fullPath: '/notes/$subject'
      preLoaderRoute: typeof NotesSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper/$id': {
      id: '/paper/$id'
      path: '/paper/$id'
      fullPath: '/paper/$id'
      preLoaderRoute: typeof PaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subject': {
      id: '/subject/$subject'
      path: '/subject/$subject'
      fullPath: '/subject/$subject'
      preLoaderRoute: typeof SubjectSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$key': {
      id: '/topics/$key'
      path: '/topics/$key'
      fullPath: '/topics/$key'
      preLoaderRoute: typeof TopicsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year/$year': {
      id: '/year/$year'
      path: '/year/$year'
      fullPath: '/year/$year'
      preLoaderRoute: typeof YearYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPdfRoute: ApiPdfRoute,
  NotesSubjectRoute: NotesSubjectRoute,
  PaperIdRoute: PaperIdRoute,
  SubjectSubjectRoute: SubjectSubjectRoute,
  TopicsKeyRoute: TopicsKeyRoute,
  YearYearRoute: YearYearRoute,
  NotesIndexRoute: NotesIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
