/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as NotesSubjectRouteImport } from './routes/notes.$subject'
import { Route as PaperIdRouteImport } from './routes/paper.$id'
import { Route as SubjectSubjectRouteImport } from './routes/subject.$subject'
import { Route as TopicsKeyRouteImport } from './routes/topics.$key'
import { Route as YearYearRouteImport } from './routes/year.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSubjectRoute = NotesSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => NotesRoute,
} as any)
const PaperIdRoute = PaperIdRouteImport.update({
  id: '/paper/$id',
  path: '/paper/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectRoute = SubjectSubjectRouteImport.update({
  id: '/subject/$subject',
  path: '/subject/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsKeyRoute = TopicsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => TopicsRoute,
} as any)
const YearYearRoute = YearYearRouteImport.update({
  id: '/year/$year',
  path: '/year/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/notes/$subject': typeof NotesSubjectRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/topics/$key': typeof TopicsKeyRoute
  '/year/$year': typeof YearYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/notes/$subject': typeof NotesSubjectRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/topics/$key': typeof TopicsKeyRoute
  '/year/$year': typeof YearYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/api/pdf': typeof ApiPdfRoute
  '/notes/$subject': typeof NotesSubjectRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/topics/$key': typeof TopicsKeyRoute
  '/year/$year': typeof YearYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/topics'
    | '/api/pdf'
    | '/notes/$subject'
    | '/paper/$id'
    | '/subject/$subject'
    | '/topics/$key'
    | '/year/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes'
    | '/topics'
    | '/api/pdf'
    | '/notes/$subject'
    | '/paper/$id'
    | '/subject/$subject'
    | '/topics/$key'
    | '/year/$year'
  id:
    | '__root__'
    | '/'
    | '/notes'
    | '/topics'
    | '/api/pdf'
    | '/notes/$subject'
    | '/paper/$id'
    | '/subject/$subject'
    | '/topics/$key'
    | '/year/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRouteWithChildren
  TopicsRoute: typeof TopicsRouteWithChildren
  ApiPdfRoute: typeof ApiPdfRoute
  PaperIdRoute: typeof PaperIdRoute
  SubjectSubjectRoute: typeof SubjectSubjectRoute
  YearYearRoute: typeof YearYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$subject': {
      id: '/notes/$subject'
      path: '/$subject'
      fullPath: '/notes/$subject'
      preLoaderRoute: typeof NotesSubjectRouteImport
      parentRoute: typeof NotesRoute
    }
    '/paper/$id': {
      id: '/paper/$id'
      path: '/paper/$id'
      fullPath: '/paper/$id'
      preLoaderRoute: typeof PaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subject': {
      id: '/subject/$subject'
      path: '/subject/$subject'
      fullPath: '/subject/$subject'
      preLoaderRoute: typeof SubjectSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$key': {
      id: '/topics/$key'
      path: '/$key'
      fullPath: '/topics/$key'
      preLoaderRoute: typeof TopicsKeyRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/year/$year': {
      id: '/year/$year'
      path: '/year/$year'
      fullPath: '/year/$year'
      preLoaderRoute: typeof YearYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NotesRouteChildren {
  NotesSubjectRoute: typeof NotesSubjectRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesSubjectRoute: NotesSubjectRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface TopicsRouteChildren {
  TopicsKeyRoute: typeof TopicsKeyRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsKeyRoute: TopicsKeyRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRouteWithChildren,
  TopicsRoute: TopicsRouteWithChildren,
  ApiPdfRoute: ApiPdfRoute,
  PaperIdRoute: PaperIdRoute,
  SubjectSubjectRoute: SubjectSubjectRoute,
  YearYearRoute: YearYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
