/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as PaperIdRouteImport } from './routes/paper.$id'
import { Route as SubjectSubjectRouteImport } from './routes/subject.$subject'
import { Route as YearYearRouteImport } from './routes/year.$year'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotesSubjectRouteImport } from './routes/notes.$subject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperIdRoute = PaperIdRouteImport.update({
  id: '/paper/$id',
  path: '/paper/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectRoute = SubjectSubjectRouteImport.update({
  id: '/subject/$subject',
  path: '/subject/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const YearYearRoute = YearYearRouteImport.update({
  id: '/year/$year',
  path: '/year/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSubjectRoute = NotesSubjectRouteImport.update({
  id: '/notes/$subject',
  path: '/notes/$subject',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/pdf': typeof ApiPdfRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/year/$year': typeof YearYearRoute
  '/notes': typeof NotesRoute
  '/notes/$subject': typeof NotesSubjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/pdf': typeof ApiPdfRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/year/$year': typeof YearYearRoute
  '/notes': typeof NotesRoute
  '/notes/$subject': typeof NotesSubjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/pdf': typeof ApiPdfRoute
  '/paper/$id': typeof PaperIdRoute
  '/subject/$subject': typeof SubjectSubjectRoute
  '/year/$year': typeof YearYearRoute
  '/notes': typeof NotesRoute
  '/notes/$subject': typeof NotesSubjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/pdf' | '/paper/$id' | '/subject/$subject' | '/year/$year' | '/notes' | '/notes/$subject'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/pdf' | '/paper/$id' | '/subject/$subject' | '/year/$year' | '/notes' | '/notes/$subject'
  id:
    | '__root__'
    | '/'
    | '/api/pdf'
    | '/paper/$id'
    | '/subject/$subject'
    | '/year/$year'
    | '/notes'
    | '/notes/$subject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPdfRoute: typeof ApiPdfRoute
  PaperIdRoute: typeof PaperIdRoute
  SubjectSubjectRoute: typeof SubjectSubjectRoute
  YearYearRoute: typeof YearYearRoute
  NotesRoute: typeof NotesRoute
  NotesSubjectRoute: typeof NotesSubjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper/$id': {
      id: '/paper/$id'
      path: '/paper/$id'
      fullPath: '/paper/$id'
      preLoaderRoute: typeof PaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subject': {
      id: '/subject/$subject'
      path: '/subject/$subject'
      fullPath: '/subject/$subject'
      preLoaderRoute: typeof SubjectSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/year/$year': {
      id: '/year/$year'
      path: '/year/$year'
      fullPath: '/year/$year'
      preLoaderRoute: typeof YearYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$subject': {
      id: '/notes/$subject'
      path: '/notes/$subject'
      fullPath: '/notes/$subject'
      preLoaderRoute: typeof NotesSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPdfRoute: ApiPdfRoute,
  PaperIdRoute: PaperIdRoute,
  SubjectSubjectRoute: SubjectSubjectRoute,
  YearYearRoute: YearYearRoute,
  NotesRoute: NotesRoute,
  NotesSubjectRoute: NotesSubjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
